
import java.io.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bostjanv
 */
public class HitriDvig extends javax.swing.JFrame {
    BufferedReader br=null;
    PrintWriter pw=null;
    /**
     * Creates new form HitriDvig
     */
    public HitriDvig() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        deset = new javax.swing.JButton();
        dvajset = new javax.swing.JButton();
        trideset = new javax.swing.JButton();
        stirideset = new javax.swing.JButton();
        petdeset = new javax.swing.JButton();
        sedemdeset = new javax.swing.JButton();
        sto = new javax.swing.JButton();
        stopetdeset = new javax.swing.JButton();
        nazaj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 500));

        deset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desetActionPerformed(evt);
            }
        });

        dvajset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dvajsetActionPerformed(evt);
            }
        });

        trideset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tridesetActionPerformed(evt);
            }
        });

        stirideset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stiridesetActionPerformed(evt);
            }
        });

        petdeset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                petdesetActionPerformed(evt);
            }
        });

        sedemdeset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sedemdesetActionPerformed(evt);
            }
        });

        sto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stoActionPerformed(evt);
            }
        });

        stopetdeset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopetdesetActionPerformed(evt);
            }
        });

        nazaj.setText("Nazaj");
        nazaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazajActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("IZBERITE KOLIČINO DVIGA:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("50 ---->");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("70 ---->");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("100 ---->");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("150 ---->");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("<---- 10");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("<---- 20");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("<---- 30");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("<---- 40");

        jButton1.setText("Prekliči");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dvajset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(trideset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stirideset, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(petdeset, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(sedemdeset, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(sto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(stopetdeset, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addComponent(nazaj))))
                        .addGap(0, 163, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deset, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(petdeset, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(sedemdeset, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(dvajset, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trideset, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4))
                        .addGap(52, 52, 52)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stirideset, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stopetdeset, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(55, 55, 55)
                .addComponent(nazaj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void desetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desetActionPerformed
      
        try{
           br=new BufferedReader(new FileReader("racuni.txt"));
           pw=new PrintWriter(new FileWriter("racuni_temp.txt"));
            int tmp;
            tmp=(int)(Login.znesek);     //prenos zneska iz login forme
            String vrstica="";
            String tab[]=null;
       
       
       if(tmp-10<0){
           jOptionPane1.showMessageDialog(null, "Na računu nimate dovolj denarja","Napaka",jOptionPane1.ERROR_MESSAGE);
           
       }
       else{
           tmp=tmp-10;
           jOptionPane1.showMessageDialog(null, "Na računu imate še "+tmp+"€","Obvestilo",jOptionPane1.INFORMATION_MESSAGE);
           
           
           
           while(br.ready()){
            vrstica=br.readLine();
            tab=vrstica.split(" ");       //iz niza nam vsebino prenese v tabelo
          if(Login.oseba.equals(tab[0])){
                Login.znesek=tmp;         //nujnuo moramo spremeniti znesek tudi na login formi ker se ta znesek ob kliku na gumb vedno prenese iz login forme
                pw.println(tab[0]+" "+tab[1]+" "+tab[2]+" "+tab[3]+" "+tab[4]+" "+tab[5]+" "+tab[6]+" "+tab[7]+" "+tab[8]+" "+(tmp));                                       //zapiši vse +nov znesek 
          }
          else{
             pw.println(vrstica); //zapiši vrstica
          }
       }
       br.close();
       pw.close();
       
       File original=new File("racuni.txt");
       original.delete();
       new File("racuni_temp.txt").renameTo(original);
       
       
         
           Bankomat bm=new Bankomat();
           bm.setVisible(true);
           dispose();
       }
      }catch(Exception e){
          
      }
    }//GEN-LAST:event_desetActionPerformed

    private void nazajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazajActionPerformed
       Bankomat bm=new Bankomat();
           bm.setVisible(true);
           dispose();
    }//GEN-LAST:event_nazajActionPerformed

    private void dvajsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dvajsetActionPerformed
        try{
           br=new BufferedReader(new FileReader("racuni.txt"));
           pw=new PrintWriter(new FileWriter("racuni_temp.txt"));
            int tmp;
            tmp=(int)(Login.znesek);     //prenos zneska iz login forme
            String vrstica="";
            String tab[]=null;
       
       
       if(tmp-20<0){
           jOptionPane1.showMessageDialog(null, "Na računu nimate dovolj denarja","Napaka",jOptionPane1.ERROR_MESSAGE);
           
       }
       else{
           tmp=tmp-20;
           jOptionPane1.showMessageDialog(null, "Na računu imate še "+tmp+"€","Obvestilo",jOptionPane1.INFORMATION_MESSAGE);
           
           
           
           while(br.ready()){
            vrstica=br.readLine();
            tab=vrstica.split(" ");       //iz niza nam vsebino prenese v tabelo
          if(Login.oseba.equals(tab[0])){
                Login.znesek=tmp;         //nujnuo moramo spremeniti znesek tudi na login formi ker se ta znesek ob kliku na gumb vedno prenese iz login forme
                pw.println(tab[0]+" "+tab[1]+" "+tab[2]+" "+tab[3]+" "+tab[4]+" "+tab[5]+" "+tab[6]+" "+tab[7]+" "+tab[8]+" "+(tmp));                                       //zapiši vse +nov znesek 
          }
          else{
             pw.println(vrstica); //zapiši vrstica
          }
       }
       br.close();
       pw.close();
       
       File original=new File("racuni.txt");
       original.delete();
       new File("racuni_temp.txt").renameTo(original);
       
       
         
           Bankomat bm=new Bankomat();
           bm.setVisible(true);
           dispose();
       }
      }catch(Exception e){
          
      }
    }//GEN-LAST:event_dvajsetActionPerformed

    private void tridesetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tridesetActionPerformed
        try{
           br=new BufferedReader(new FileReader("racuni.txt"));
           pw=new PrintWriter(new FileWriter("racuni_temp.txt"));
            int tmp;
            tmp=(int)(Login.znesek);     //prenos zneska iz login forme
            String vrstica="";
            String tab[]=null;
       
       
       if(tmp-30<0){
           jOptionPane1.showMessageDialog(null, "Na računu nimate dovolj denarja","Napaka",jOptionPane1.ERROR_MESSAGE);
           
       }
       else{
           tmp=tmp-30;
           jOptionPane1.showMessageDialog(null, "Na računu imate še "+tmp+"€","Obvestilo",jOptionPane1.INFORMATION_MESSAGE);
           
           
           
           while(br.ready()){
            vrstica=br.readLine();
            tab=vrstica.split(" ");       //iz niza nam vsebino prenese v tabelo
          if(Login.oseba.equals(tab[0])){
                Login.znesek=tmp;         //nujnuo moramo spremeniti znesek tudi na login formi ker se ta znesek ob kliku na gumb vedno prenese iz login forme
                pw.println(tab[0]+" "+tab[1]+" "+tab[2]+" "+tab[3]+" "+tab[4]+" "+tab[5]+" "+tab[6]+" "+tab[7]+" "+tab[8]+" "+(tmp));                                       //zapiši vse +nov znesek 
          }
          else{
             pw.println(vrstica); //zapiši vrstica
          }
       }
       br.close();
       pw.close();
       
       File original=new File("racuni.txt");
       original.delete();
       new File("racuni_temp.txt").renameTo(original);
       
       
         
           Bankomat bm=new Bankomat();
           bm.setVisible(true);
           dispose();
       }
      }catch(Exception e){
          
      }
    }//GEN-LAST:event_tridesetActionPerformed

    private void stiridesetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stiridesetActionPerformed
        try{
           br=new BufferedReader(new FileReader("racuni.txt"));
           pw=new PrintWriter(new FileWriter("racuni_temp.txt"));
            int tmp;
            tmp=(int)(Login.znesek);     //prenos zneska iz login forme
            String vrstica="";
            String tab[]=null;
       
       
       if(tmp-40<0){
           jOptionPane1.showMessageDialog(null, "Na računu nimate dovolj denarja","Napaka",jOptionPane1.ERROR_MESSAGE);
           
       }
       else{
           tmp=tmp-40;
           jOptionPane1.showMessageDialog(null, "Na računu imate še "+tmp+"€","Obvestilo",jOptionPane1.INFORMATION_MESSAGE);                      
           
            while(br.ready()){
                vrstica=br.readLine();
                tab=vrstica.split(" ");       //iz niza nam vsebino prenese v tabelo
                if(Login.oseba.equals(tab[0])){
                    Login.znesek=tmp;         //nujnuo moramo spremeniti znesek tudi na login formi ker se ta znesek ob kliku na gumb vedno prenese iz login forme
                    pw.println(tab[0]+" "+tab[1]+" "+tab[2]+" "+tab[3]+" "+tab[4]+" "+tab[5]+" "+tab[6]+" "+tab[7]+" "+tab[8]+" "+(tmp));                                       //zapiši vse +nov znesek 
                }
                else{
                pw.println(vrstica); //zapiši vrstica
                }
            }
       br.close();
       pw.close();
       
       File original=new File("racuni.txt");
       original.delete();
       new File("racuni_temp.txt").renameTo(original);
       
       
         
           Bankomat bm=new Bankomat();
           bm.setVisible(true);
           dispose();
       }
      }catch(Exception e){
          
      }
    }//GEN-LAST:event_stiridesetActionPerformed

    private void petdesetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_petdesetActionPerformed
        try{
           br=new BufferedReader(new FileReader("racuni.txt"));
           pw=new PrintWriter(new FileWriter("racuni_temp.txt"));
            int tmp;
            tmp=(int)(Login.znesek);     //prenos zneska iz login forme
            String vrstica="";
            String tab[]=null;
       
       
       if(tmp-50<0){
           jOptionPane1.showMessageDialog(null, "Na računu nimate dovolj denarja","Napaka",jOptionPane1.ERROR_MESSAGE);
           
       }
       else{
           tmp=tmp-50;
           jOptionPane1.showMessageDialog(null, "Na računu imate še "+tmp+"€","Obvestilo",jOptionPane1.INFORMATION_MESSAGE);
           
           
           
           while(br.ready()){
            vrstica=br.readLine();
            tab=vrstica.split(" ");       //iz niza nam vsebino prenese v tabelo
          if(Login.oseba.equals(tab[0])){
                Login.znesek=tmp;         //nujnuo moramo spremeniti znesek tudi na login formi ker se ta znesek ob kliku na gumb vedno prenese iz login forme
                pw.println(tab[0]+" "+tab[1]+" "+tab[2]+" "+tab[3]+" "+tab[4]+" "+tab[5]+" "+tab[6]+" "+tab[7]+" "+tab[8]+" "+(tmp));                                       //zapiši vse +nov znesek 
          }
          else{
             pw.println(vrstica); //zapiši vrstica
          }
       }
       br.close();
       pw.close();
       
       File original=new File("racuni.txt");
       original.delete();
       new File("racuni_temp.txt").renameTo(original);
       
       
         
           Bankomat bm=new Bankomat();
           bm.setVisible(true);
           dispose();
       }
      }catch(Exception e){
          
      }
    }//GEN-LAST:event_petdesetActionPerformed

    private void sedemdesetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sedemdesetActionPerformed
        try{
           br=new BufferedReader(new FileReader("racuni.txt"));
           pw=new PrintWriter(new FileWriter("racuni_temp.txt"));
            int tmp;
            tmp=(int)(Login.znesek);     //prenos zneska iz login forme
            String vrstica="";
            String tab[]=null;
       
       
       if(tmp-70<0){
           jOptionPane1.showMessageDialog(null, "Na računu nimate dovolj denarja","Napaka",jOptionPane1.ERROR_MESSAGE);
           
       }
       else{
           tmp=tmp-70;
           jOptionPane1.showMessageDialog(null, "Na računu imate še "+tmp+"€","Obvestilo",jOptionPane1.INFORMATION_MESSAGE);
           
           
           
           while(br.ready()){
            vrstica=br.readLine();
            tab=vrstica.split(" ");       //iz niza nam vsebino prenese v tabelo
          if(Login.oseba.equals(tab[0])){
                Login.znesek=tmp;         //nujnuo moramo spremeniti znesek tudi na login formi ker se ta znesek ob kliku na gumb vedno prenese iz login forme
                pw.println(tab[0]+" "+tab[1]+" "+tab[2]+" "+tab[3]+" "+tab[4]+" "+tab[5]+" "+tab[6]+" "+tab[7]+" "+tab[8]+" "+(tmp));                                       //zapiši vse +nov znesek 
          }
          else{
             pw.println(vrstica); //zapiši vrstica
          }
       }
       br.close();
       pw.close();
       
       File original=new File("racuni.txt");
       original.delete();
       new File("racuni_temp.txt").renameTo(original);
       
       
         
           Bankomat bm=new Bankomat();
           bm.setVisible(true);
           dispose();
       }
      }catch(Exception e){
          
      }
    }//GEN-LAST:event_sedemdesetActionPerformed

    private void stoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stoActionPerformed
        try{
           br=new BufferedReader(new FileReader("racuni.txt"));
           pw=new PrintWriter(new FileWriter("racuni_temp.txt"));
            int tmp;
            tmp=(int)(Login.znesek);     //prenos zneska iz login forme
            String vrstica="";
            String tab[]=null;
       
       
       if(tmp-100<0){
           jOptionPane1.showMessageDialog(null, "Na računu nimate dovolj denarja","Napaka",jOptionPane1.ERROR_MESSAGE);
           
       }
       else{
           tmp=tmp-100;
           jOptionPane1.showMessageDialog(null, "Na računu imate še "+tmp+"€","Obvestilo",jOptionPane1.INFORMATION_MESSAGE);
           
           
           
           while(br.ready()){
            vrstica=br.readLine();
            tab=vrstica.split(" ");       //iz niza nam vsebino prenese v tabelo
          if(Login.oseba.equals(tab[0])){
                Login.znesek=tmp;         //nujnuo moramo spremeniti znesek tudi na login formi ker se ta znesek ob kliku na gumb vedno prenese iz login forme
                pw.println(tab[0]+" "+tab[1]+" "+tab[2]+" "+tab[3]+" "+tab[4]+" "+tab[5]+" "+tab[6]+" "+tab[7]+" "+tab[8]+" "+(tmp));                                       //zapiši vse +nov znesek 
          }
          else{
             pw.println(vrstica); //zapiši vrstica
          }
       }
       br.close();
       pw.close();
       
       File original=new File("racuni.txt");
       original.delete();
       new File("racuni_temp.txt").renameTo(original);
       
       
         
           Bankomat bm=new Bankomat();
           bm.setVisible(true);
           dispose();
       }
      }catch(Exception e){
          
      }
    }//GEN-LAST:event_stoActionPerformed

    private void stopetdesetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopetdesetActionPerformed
        try{
           br=new BufferedReader(new FileReader("racuni.txt"));
           pw=new PrintWriter(new FileWriter("racuni_temp.txt"));
            int tmp;
            tmp=(int)(Login.znesek);     //prenos zneska iz login forme
            String vrstica="";
            String tab[]=null;
       
       
       if(tmp-150<0){
           jOptionPane1.showMessageDialog(null, "Na računu nimate dovolj denarja","Napaka",jOptionPane1.ERROR_MESSAGE);
           
       }
       else{
           tmp=tmp-150;
           jOptionPane1.showMessageDialog(null, "Na računu imate še "+tmp+"€","Obvestilo",jOptionPane1.INFORMATION_MESSAGE);
           
           
           
           while(br.ready()){
            vrstica=br.readLine();
            tab=vrstica.split(" ");       //iz niza nam vsebino prenese v tabelo
          if(Login.oseba.equals(tab[0])){
                Login.znesek=tmp;         //nujnuo moramo spremeniti znesek tudi na login formi ker se ta znesek ob kliku na gumb vedno prenese iz login forme
                pw.println(tab[0]+" "+tab[1]+" "+tab[2]+" "+tab[3]+" "+tab[4]+" "+tab[5]+" "+tab[6]+" "+tab[7]+" "+tab[8]+" "+(tmp));                                       //zapiši vse +nov znesek 
          }
          else{
             pw.println(vrstica); //zapiši vrstica
          }
       }
       br.close();
       pw.close();
       
       File original=new File("racuni.txt");
       original.delete();
       new File("racuni_temp.txt").renameTo(original);
       
       
         
           Bankomat bm=new Bankomat();
           bm.setVisible(true);
           dispose();
       }
      }catch(Exception e){
          
      }
    }//GEN-LAST:event_stopetdesetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            Bankomat bm=new Bankomat();
            bm.setVisible(true);
            dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HitriDvig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HitriDvig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HitriDvig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HitriDvig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HitriDvig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deset;
    private javax.swing.JButton dvajset;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nazaj;
    private javax.swing.JButton petdeset;
    private javax.swing.JButton sedemdeset;
    private javax.swing.JButton stirideset;
    private javax.swing.JButton sto;
    private javax.swing.JButton stopetdeset;
    private javax.swing.JButton trideset;
    // End of variables declaration//GEN-END:variables
}
