

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bostjanv
 */
public class Prenos extends javax.swing.JFrame {
    BufferedReader br=null;
    PrintWriter pw=null;
    /**
     * Creates new form Prenos
     */
    
            JComboBox jcb= new JComboBox();
            String cont[]={"one","two","three"};

    public Prenos() throws FileNotFoundException, IOException {
        
        
        initComponents();
        
        //AutoCompleteDecorator.decorate(jComboBoxPlacnik);
        //jComboBoxPlacnik.addItem("saa");
        
        double znesek;        //globalna spremenlljivka kamor shranimo nas znesek na trr-ju
        String oseba="";
        String pwd;           //spremenljivka kamor shranimo geslo iz datoteke
        String pinL;          //spremenljivka pinL kamor shranimo pin ki ga preberemo iz datoteke
        
            br=new BufferedReader(new FileReader("racuni.txt")); // datoteka naj bo v ANSI oz. določi tip kodiranja pri pisanju v datoteko (obrazec Registracija)
            boolean kontrola=false;
            Scanner sc=null;
            String vrstica="";
            while(br.ready()){          //beremo vrstico po vrstico iz datoteke
                   vrstica=br.readLine();               
                   sc= new Scanner(vrstica);
                   oseba=sc.next();
                   pwd=sc.next();
                   pinL=sc.next();
                   
                   jComboBoxPlacnik.addItem(oseba);
                   jComboBoxPrejemnik.addItem(oseba);
      
                }
            sc.close();
            br.close();
            
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jPanelPrenos = new javax.swing.JPanel();
        jComboBoxPlacnik = new javax.swing.JComboBox<>();
        jComboBoxPrejemnik = new javax.swing.JComboBox<>();
        znesek = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPrenos.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanelPrenos.setPreferredSize(new java.awt.Dimension(600, 400));

        znesek.setToolTipText("");
        znesek.setHighlighter(null);

        jButton1.setText("Prenos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Znesek");

        jLabel2.setText("Plačnik");

        jLabel3.setText("Prejemnik");

        jButton2.setText("Prekliči");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("PRENOS SREDSTEV");

        javax.swing.GroupLayout jPanelPrenosLayout = new javax.swing.GroupLayout(jPanelPrenos);
        jPanelPrenos.setLayout(jPanelPrenosLayout);
        jPanelPrenosLayout.setHorizontalGroup(
            jPanelPrenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrenosLayout.createSequentialGroup()
                .addGroup(jPanelPrenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPrenosLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54)
                        .addComponent(znesek, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE))
                    .addGroup(jPanelPrenosLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanelPrenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxPlacnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelPrenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxPrejemnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(124, 124, 124))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrenosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelPrenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrenosLayout.createSequentialGroup()
                        .addGroup(jPanelPrenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(258, 258, 258))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrenosLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(209, 209, 209))))
        );
        jPanelPrenosLayout.setVerticalGroup(
            jPanelPrenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrenosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel7)
                .addGap(32, 32, 32)
                .addGroup(jPanelPrenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanelPrenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxPlacnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPrejemnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanelPrenosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(znesek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(49, 49, 49)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelPrenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Bankomat log=new Bankomat();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{

            //jOptionPane1.showMessageDialog(null, "Plačnik in prejemnik sta enaka","Napaka",jOptionPane1.ERROR_MESSAGE);
            br=new BufferedReader(new FileReader("racuni.txt"));
            pw=new PrintWriter(new FileWriter("racuni_temp.txt"));
            String tab[]=null;
            String vrstica="";
            int tmp=Integer.parseInt(znesek.getText());      //prenos vrednosti iz polja na obrazcu v spremenljivko
            boolean kontrola=true;
            /*tmp=(int)(Login.znesek);     //prenos zneska iz login forme

            tmp=(int)(Login.znesek);     //prenos zneska iz login forme
            String vrstica="";
            String tab[]=null;*/

            //test
            //jLabel1.setText("teeest");

            //jLabel1.setText(jComboBoxPlacnik.getSelectedItem().toString());
            //System.out.println("Teeeeeeeeeeeest");
            if(jComboBoxPlacnik.getSelectedItem().toString().equals(jComboBoxPrejemnik.getSelectedItem().toString())){
                jOptionPane1.showMessageDialog(null, "Plačnik in prejemnik sta enaka","Napaka",jOptionPane1.ERROR_MESSAGE);
                kontrola=false;
            }


            if(kontrola){   //if(kontrola==true)
            while(br.ready()){
                vrstica=br.readLine();
                tab=vrstica.split(" ");       //iz niza nam vsebino prenese v tabelo
                if(jComboBoxPlacnik.getSelectedItem().toString().equals(tab[0])){
                    if(Integer.parseInt(tab[9])-tmp>=0)
                        pw.println(tab[0]+" "+tab[1]+" "+tab[2]+" "+tab[3]+" "+tab[4]+" "+tab[5]+" "+tab[6]+" "+tab[7]+" "+tab[8]+" "+(Integer.parseInt(tab[9])-tmp)); //zapiši nov znesek
                    else{
                        pw.println(vrstica); //zapiši vrstica
                        jOptionPane1.showMessageDialog(null, "Transakcija se ne more izvesti, ker plačnik nima dovolj sredstev na računu. Plačnik ima na računu še "+Integer.parseInt(tab[9])+" EUR","Napaka",jOptionPane1.ERROR_MESSAGE);   
                        kontrola=false;
                    }
                }
                else if(jComboBoxPrejemnik.getSelectedItem().toString().equals(tab[0])){
                    pw.println(tab[0]+" "+tab[1]+" "+tab[2]+" "+tab[3]+" "+tab[4]+" "+tab[5]+" "+tab[6]+" "+tab[7]+" "+tab[8]+" "+(Integer.parseInt(tab[9])+tmp));
                }
                else{
                    pw.println(vrstica); //zapiši vrstica
                }
            }
            }
            br.close();
            pw.close();

            
            File original=new File("racuni.txt");
            original.delete();
            new File("racuni_temp.txt").renameTo(original);
           
            if(kontrola){
            jOptionPane1.showMessageDialog(null,
                "Transakcija je zaključena."+" Uporabnik "+ jComboBoxPlacnik.getSelectedItem().toString() +" je prenesel "+tmp+" EUR na uporabnika "+jComboBoxPrejemnik.getSelectedItem().toString(),
                "Informacija",jOptionPane1.INFORMATION_MESSAGE);
            }
            znesek.setText("");

        }catch(Exception e){
            jOptionPane1.showMessageDialog(null, "Napaka.","Napaka",jOptionPane1.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {

            
      
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prenos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prenos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prenos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prenos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Prenos().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Prenos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxPlacnik;
    private javax.swing.JComboBox<String> jComboBoxPrejemnik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanelPrenos;
    private javax.swing.JTextField znesek;
    // End of variables declaration//GEN-END:variables
}
