
import java.awt.Cursor;
import java.io.*;
import java.util.Scanner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bostjanv
 */
public class ZamenjavaPina extends javax.swing.JFrame {
    
    /**
     * Creates new form ZamenjavaPina
     */
    public ZamenjavaPina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pin1 = new javax.swing.JPasswordField();
        pin2 = new javax.swing.JPasswordField();
        vredu = new javax.swing.JButton();
        nazaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Zamenjava PIN-a");

        jLabel2.setText("Vnesite PIN:");

        jLabel3.setText("Potrdite nov PIN:");

        pin1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pin1KeyTyped(evt);
            }
        });

        pin2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pin2KeyTyped(evt);
            }
        });

        vredu.setText("Vredu");
        vredu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vreduMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vreduMouseExited(evt);
            }
        });
        vredu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vreduActionPerformed(evt);
            }
        });

        nazaj.setText("Nazaj");
        nazaj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nazajMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nazajMouseExited(evt);
            }
        });
        nazaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nazajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pin1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(pin2))))
                .addContainerGap(188, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vredu)
                .addGap(139, 139, 139)
                .addComponent(nazaj)
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vredu)
                    .addComponent(nazaj))
                .addGap(69, 69, 69))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pin1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pin1KeyTyped
        if(pin1.getText().length()>=4)
        evt.consume();
    }//GEN-LAST:event_pin1KeyTyped

    private void pin2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pin2KeyTyped
        if(pin2.getText().length()>=4)
        evt.consume();
    }//GEN-LAST:event_pin2KeyTyped

    private void vreduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vreduActionPerformed
       String pin=Login.pinL;
       String vrstica;
       
       BufferedReader br=null;
       PrintWriter pw=null;
       Scanner vh=null;
       
       try{
         
          if(!(pin1.getText().equals(pin2.getText()) && pin1.getText().length()==4 && pin2.getText().length()==4)){
           jOptionPane1.showMessageDialog(null,"Vnesena PIN-a se ne ujemata","Napaka",jOptionPane1.ERROR_MESSAGE);   
          }
          else{
           
          br=new BufferedReader(new FileReader("racuni.txt"));
          pw=new PrintWriter(new FileWriter("racuni_temp.txt"));
        
          while(br.ready()){
            vrstica=br.readLine();
           vh=new Scanner(vrstica);         //scanner uporabimo da z metodo next() dostopimo doprvega zapisa v vrstici
           if(vh.next().equals(Login.oseba)){       //preverimo ali je prvi zapis v vrstici enak tistemu pri prijavi(uporabniško ime)
               //metodo replaceFirst uporabimo zato ker je lahko  pin tudi enak znesku. v primeru uporabe replaceAll bi prišlo do napake
               //z metodo replace first spremenimo obstoječi pin z novim vnesenim pinom, tu lahko uporabimo pin1 ali pin2
               vrstica=vrstica.replaceFirst(pin,pin1.getText());        
               Login.pinL=pin1.getText();       //spremenimo tudi pin na login formi
               
           }
           pw.println(vrstica);
           
            }   
       br.close();
       pw.close();
       vh.close();
      
       File original=new File("racuni.txt");
       original.delete();
       new File("racuni_temp.txt").renameTo(original);
       
       jOptionPane1.showMessageDialog(null, "Vaš PIN je "+pin1.getText(),"Sprememba PIN-a",jOptionPane1.INFORMATION_MESSAGE);
       
       Bankomat bm=new Bankomat();
       bm.setVisible(true);
       dispose();
       }
      
       
       }
       
       catch(Exception e){
           
       }
       
    }//GEN-LAST:event_vreduActionPerformed

    private void nazajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nazajActionPerformed
       Bankomat bm=new Bankomat();
       bm.setVisible(true);
       dispose();
    }//GEN-LAST:event_nazajActionPerformed

    private void vreduMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vreduMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_vreduMouseEntered

    private void vreduMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vreduMouseExited
         setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_vreduMouseExited

    private void nazajMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nazajMouseEntered
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_nazajMouseEntered

    private void nazajMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nazajMouseExited
       setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_nazajMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZamenjavaPina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZamenjavaPina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZamenjavaPina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZamenjavaPina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZamenjavaPina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nazaj;
    private javax.swing.JPasswordField pin1;
    private javax.swing.JPasswordField pin2;
    private javax.swing.JButton vredu;
    // End of variables declaration//GEN-END:variables
}
